### ISSUE TITLE
Export data into a new/existing pool

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#1915] opened 2021-11-01 17:30 UTC
Add ability to export the full results of a query into a new or existing pool. This will speed up the workflow where you ingest into a "raw" pool, find the clean data with a filter or shaper, then need to re-write it into a new pool.

**Comment by philrz** [comment] 2024-04-19 21:11
This is a duplicate of #2769 and was addressed in #2985.

**Closed by philrz** 2024-04-19 21:11 UTC
